### ISSUE TITLE
info or geo should not print to console.

### ISSUE THREAD

**Issue by dominix** [ipinfo/perl#4]
when using Geo::IPinfo the method info  return the right detailed object but it unnecessarily print it to console.
I end with  plenty of 
```
{
  "ip": "202.3.225.115",
  "city": "Papeete",
  "region": "Îles du Vent",
  "country": "PF",
  "loc": "-17.5373,-149.5665",
  "timezone": "Pacific/Tahiti"
}
```
on the screen instead of just populating my variables.
is it possible to stop this printing ?

**Comment by UmanShahzad** [comment]
I guess it's just this line? https://github.com/ipinfo/perl/blob/master/Geo-IPinfo/lib/Geo/IPinfo.pm#L196

**Comment by gnazarey** [comment]
I will be requesting a pull to fix this issue.

**Comment by UmanShahzad** [comment]
Thanks a lot @gnazarey !
